spring:
   application:
            name: microsvc-static-1
   main:
     allow-bean-definition-overriding: true
   security:
     user:
       name: Admin2
       password: admin2

server:
  port: 7050
  ssl:
#   key-store-type: PKCS12
#   key-store: classpath:keystore/testssl2.keystore
#   key-store-password: 123456
#   key-alias: testssl2
#   enabled: true
   key-store-type: JKS
   key-store: classpath:store/ssecty_keystore1.jks
   key-store-password: changeit
   key-alias: localhost
   enabled: true
   trust-store-type: JKS
   trust-store: classpath:store/ssecty_truststore1.jks
   trust-store-password: changeit
   client-auth: need

app:
 env:
  color: green
  servUrl1: http://localhost:7051/microsvc-static-2
  at_username: user1
  at_password: pass@123
  at_grant_type: password
  at_client_id: myclient
  at_Url: http://192.168.0.111:8080/auth/realms/myrealm/protocol/openid-connect/token
  itrLimit: 10
  delay: 5
  trds: 2

logging:
    file:
      name: logs/microsvc-static-1/microsvc-static-1.log
      path: logs/microsvc-static-1
    max-size: 2048
    max-history: 5
    level:
        root: ERROR
        org.springframework.web: ERROR
        com.microsvc: INFO
        org.hibernate: ERROR
#    pattern:
#       console: 


