spring:
   application:
            name: microsvc-static-1
   main:
     allow-bean-definition-overriding: true

server:
  port: 7050
  ssl:
   key-store-type: PKCS12
   key-store: classpath:keystore/testssl2.keystore
   key-store-password: 123456
   key-alias: testssl2
   enabled: true
#   trust-store: /usr/lib/jvm/java-17-openjdk-amd64/lib/security/cacerts
#   trust-store-password: abcdefghw
#    enabled: true
#    key-alias: skipper
#    key-store: "classpath:keystore/skipper.keystore"
#    key-store-type: jks
#    key-store-password: skipper
#    key-password: skipper   

#trust:
# store:
#  location: classpath:keystore/testssl.keystore
#  password: testssl
app:
 env:
  color: green
  servUrl1: http://localhost:7051/microsvc-static-2
  at_username: user1
  at_password: pass@123
  at_grant_type: password
  at_client_id: myclient
  at_Url: http://192.168.0.111:8080/auth/realms/myrealm/protocol/openid-connect/token
  itrLimit: 10
  delay: 5
  trds: 2

logging:
    file:
      name: logs/microsvc-static-1/microsvc-static-1.log
      path: logs/microsvc-static-1
    max-size: 2048
    max-history: 5
    level:
        root: ERROR
        org.springframework.web: ERROR
        com.microsvc: INFO
        org.hibernate: ERROR
#    pattern:
#       console: 


