spring:
   application:
     name: microsvc-static-1
   main:
     allow-bean-definition-overriding: true
   datasource:
     username: postgres
     password: postgres
     url: jdbc:postgresql://10.96.229.228:5432/tempdb
     
server:
  port: 7050
app:
 env:
  color: ENC(lgEuNgkWf5XNa3h6CMTptg==)
  servUrl1: http://localhost:7051/microsvc-static-2
  at_username: user1
  at_password: pass@123
  at_grant_type: password
  at_client_id: myclient
  at_Url: http://192.168.0.111:8080/auth/realms/myrealm/protocol/openid-connect/token
  itrLimit: 10

logging:
    file:
      name: logs/microsvc-static-1/microsvc-static-1.log
      path: logs/microsvc-static-1
    max-size: 2048
    max-history: 5
    level:
        root: ERROR
        org.springframework.web: ERROR
        com.microsvc: INFO
        org.hibernate: ERROR
#    pattern:
#       console: 
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator  
